# About
title: Open APIs for telecoms
sub_title: Oppertunities for new services & stronger digital rights
description: By doing X, the telecoms sector can do Y andf Z enabling Some things that are areally important
url: CHANGEME

# Pages, and what order they're in
pages:
  - "Open APIs for telecoms"
  - "An introduction to Open APIs"
  - "Scenario 1: Choosing the best mobile network operator"
  - "Scenario 2: Managing utility bills in a shared household"
  - "Scenario 3: Improving a city's air quality using bulk location data from mobile phones"
  - "Potential design patterns for open APIs in the utilities sector"
  - "Potential open APIs for the telecoms sector"
  - "Summary: building the future"
  - "Appendix: About this research"

# Design
show_collaborator_logo: true
collaborator_name: Open Data Institute
collaborator_logo_url: "https://s3-eu-west-1.amazonaws.com/projectsbyif.com/longform/openapis.projectsbyif.com/open-data-institute.png"
collaborator_url: "https://theodi.org"

# Licence
show_licence: true
licence_text: "This report is licenced under Creative Commons Attribution 4.0 International"
licence_url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png

# TOC
show_table_of_contents: true

# Social media links
twitter_card_handle: @projectsbyif
