# About
title: Designing for Open APIs
description: CHANGEME
url: CHANGEME
collaborator_name: CHANGEME

# Pages, and what order they're in
pages:
  - Designing for Open APIs
  - Design patterns for Open APIs
  - Choosing the best provider
  - Managing a shared household
  - Improving a city's air quality
  - Potential new APIs
  - Notes for Regulators

# Design
show_collaborator_logo: false
collaborator_logo_url: ""
collaborator_url: ""

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png

# Social media links
twitter_card_handle: @projectsbyif
