# About
title: Open APIs for telecoms enabling new digital rights
description: CHANGEME
url: CHANGEME
collaborator_name: CHANGEME

# Pages, and what order they're in
pages:
  - "Open APIs for telecoms enabling new digital rights"
  - "Introduction to Open APIs"
  - "Case study 1: Choosing the best provider"
  - "Case study 2: Managing a shared household"
  - "Case study 3: Improving a city's air quality"
  - "Appendix: About this research"
  - "Appendix: Design patterns in these case studies"
  - "Appendix: Potential APIs for the telecoms sector"
  - "Summary: building the future"

# Design
show_collaborator_logo: false
collaborator_logo_url: ""
collaborator_url: ""

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png

# Social media links
twitter_card_handle: @projectsbyif
